### ISSUE TITLE
Tests seem to pass on CI, but fail when using make locally

### ISSUE THREAD

**Issue by cuminandpaprika** [arr-ai/arrai#105]
### Steps to Reproduce
1. git checkout master
2. make test
3. Tests fail

**Expected behavior:**
- Tests should fail on CI if they fail via the make file

**Actual behavior:**
- Tests pass on CI https://github.com/arr-ai/arrai/pull/102/checks?check_run_id=569350764

* Debug&Crash Output
Test failure output
```
go test  -tags timingsensitive ./...
ok  	github.com/arr-ai/arrai/cmd/arrai	0.380s
?   	github.com/arr-ai/arrai/engine	[no test files]
ok  	github.com/arr-ai/arrai/rel	0.042s
--- FAIL: TestImportCache (0.14s)
    import_cache_test.go:51:
        	Error Trace:	import_cache_test.go:51
        	Error:      	Not equal:
        	            	expected: []string{"10 > a 1", "30 > b", "40 > c", "50 > d 1", "80 < b", "90 < d 1", "90 > d 2", "110 < a 1", "130 < d 2", "140 < c"}
        	            	actual  : []string{"10 > a 1", "30 > b", "40 > c", "50 > d 1", "80 < b", "90 < d 1", "90 > d 2", "110 < a 1", "132 < d 2", "142 < c"}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -9,4 +9,4 @@
        	            	  (string) (len=9) "110 < a 1",
        	            	- (string) (len=9) "130 < d 2",
        	            	- (string) (len=7) "140 < c"
        	            	+ (string) (len=9) "132 < d 2",
        	            	+ (string) (len=7) "142 < c"
        	            	 }
        	Test:       	TestImportCache
FAIL
FAIL	github.com/arr-ai/arrai/syntax	10.288s
?   	github.com/arr-ai/arrai/tools/module	[no test files]
ok  	github.com/arr-ai/arrai/translate	0.092s
FAIL
make: *** [test] Error 1
```

### Your Environments
```sh
$ go version
go version go1.13.9 darwin/amd64

```

**Comment by ChloePlanet** [comment]
It's because that’s a timing-sensitive test in `make`. It isn’t guaranteed to always work and is disabled in CI.
```
$ make
go test -tags timingsensitive ./...
```

Solution:
Add another dedicated make command for time-sensitive test and disable it in `make`.

**Comment by andrewemeryanz** [comment]
@ChloePlanet What do you mean by timing-sensitive? Do you mean there's a race condition in the test or that the test takes a long time to run?

**Comment by ChloePlanet** [comment]
The test takes a long time to run. It tests importing external packages from internet.

**Comment by andrewemeryanz** [comment]
Rather than avoiding the test, can the test be mocked by serving up a local file that's consumed by the test case (or something similar)?

**Comment by springwiz** [comment]
If the test case actually tests importing external packages from internet then mocking the test case with a local file wouldn't help, we could rather define a new make target to make such testing explicit.

**Comment by andrewemeryanz** [comment]
I assume the test is testing the retrieval of a package over the network. If you make the test case dynamic (so that the url it's trying to import points to your locally hosted file) then you have an equivalent test without the dependency of the external network. Is this possible?

**Comment by andrewemeryanz** [comment]
Ok. I should have taken a look at the test first before commenting. The issue doesn't have to do with the length of time the test takes to retrieve an external resource. The issue is caused because the comparison string includes timing values (eg. the `10` in `10 > a 1`) so if execution is slow then the test will fail. 

A simple solution that doesn't compromise the integrity of the test would be to remove the timing values. Run it past the original author: @marcelocantos
