### ISSUE TITLE
Revise conditional operator syntax

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#114]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Use-cases
Current conditional operator syntax inverts the reading flow, placing the conditional after the successful case: `x if cond1 else y if cond2 else z`. This confuses even readers who are well versed in this syntactic form.

Change the syntax to a form that follows the natural reading order.

Proposed syntax: `cond (cond1: x, cond2: y, *: z)`. Also consider supporting a control expression: `control_var cond (1: x, 2: y, *: z)`. In both cases `*: z` is optional, defaulting to `*: false` (which is the same as {}).

**Comment by ericzhang6222** [comment]
> Let's change the keyword to cond. It more unusual, therefore less likely to be chosen as a regular name, and avoids accidental comparisons with the switch statement in other languages.
