### ISSUE TITLE
Merge operator

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#133]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Use-cases

Merging tuples and functions is desirable. Merging two tuples combines all rhs attributes and any lhs attributes whose name isn't on the rhs into a new tuple. For example, merging `(a: 1, b: 2)` and `(b: 3, c: 4)` produces `(a: 1, b: 3, c: 4)`.

This is already implemented as `+`, but this operator should be strictly reserved for its common numeric interpretation. In future, libraries should be able to implement arithmetic over tuples, e.g.: `(x: 1, y: 2) + (x: 3, y: -1) = (x: 4, y: 1)`, which would conflict with the current `+` semantic.

### Proposed Solution

The proposed syntax is `a +> b`. The syntactic asymmetry emphasises the semantic asymmetry (b's attributes take priority over a's).

### Alternatives Considered

`a +> b` is slightly confusing since the directionality might give the impression that a's attributes override b's.

| syntax | notes |
|:-|:-|
| `a <+ b` | Infeasible, since it currently parses as `a < +b`. |
| `a +< b` | Confusing. Doesn't look like a single operator. |
| `a + b` | As discussed above, this should be reserved for the common arithmetic meaning. |
| `a ++ b` | Applies to special sets (arrays, strings, ...) and has a different semantic (applies an offset to every `@` on the RHS). |
| `a merge b` | Adds a keyword and is a bit verbose for what is likely to be a very common operation, especially considering #485. |

### Possible extension to dictionaries

Dictionaries have similar behaviour to tuples. `+>` could also be made to work for them. This technically violates the principle of syntactic transparency (what you get can be inferred directly from what you see). But tuples and dicts are close enough cousins that it's probably OK to make an exception for them.

**Comment by ericzhang6222** [comment]
@marcelocantos, looks like it is not good to add this feature to dictionaries as now arr.ai dictionary can have duplicated keys `func NewDict(allowDupKeys bool, entries ...DictEntryTuple) Set`.

**Comment by ericzhang6222** [comment]
> @marcelocantos, looks like it is not good to add this feature to dictionaries as now arr.ai dictionary can have duplicated keys `func NewDict(allowDupKeys bool, entries ...DictEntryTuple) Set`.

Will add support on dict too as it is necessary.
