### ISSUE TITLE
Includes source context when arr.ai evaluations crash

### ISSUE THREAD

**Issue by ChloePlanet** [arr-ai/arrai#136]
### Current arrai Version
v0.1.0

### Use-cases
Includes filename, line number, column number in evaluation crash error message.

### References
- #88

**Comment by ChloePlanet** [comment]
Potential solution 1:
1. Add field `scanner Scanner` to each exprs (27 in total).
2. Populate `scanner` in [compiling progress](https://github.com/arr-ai/arrai/blob/master/syntax/compile.go#L57).
3. update `Expr` interface and add `Scanner()` function to all the 27 exprs.
```diff
type Expr interface {
	// Require a String() method.
	fmt.Stringer

	// Eval evaluates the expr in a given scope.
	Eval(local Scope) (Value, error)

+	Scanner() parser.Scanner
}
```
4. Include `e.Scanner().Context()` in `e.Eval(local Scope)` error.

**Comment by marcelocantos** [comment]
Potential solution 1 is a bit of work, but I think it's the right approach. A common struct used as an embedded field should make it pretty easy to implement per expr type.

**Comment by ChloePlanet** [comment]
If a tuple literal has a repeated attribute name, the error should report both attributes, even if they're on different lines: #145 
```
(
    a: 1,
    b: 2,
    c: 3,
    d: 4,
    w: 99,
    x: 98,
    y: 97,
    a: 96,
)
```

**Comment by ChloePlanet** [comment]
I realized I also need to add `Scanner()` function to all the `Value` since `Expr` embeds in `Value`. And I don't feel quite correct to include the common struct in `Number` since `Number` is a `float64`.

**Comment by marcelocantos** [comment]
Values never produce errors, so perhaps they can return an empty scanner for now. Or maybe the method can be `Scanner() (_ parser.Scanner, has bool)`.

**Comment by marcelocantos** [comment]
On the flip side, the long term goal is to support `Scanner()` on every node, including values, so the method should probably stay as is, and use a short term workaround to represent an empty Scanner for values on the assumption that it will never actually get called (maybe even `panic("not implemented")`).
