### ISSUE TITLE
Allow a comma-list of values per cond case

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#160]
E.g.:
```
x cond (
    1: "lo",
    (2, 3): "med",
    *: "hi"
)
```

The parentheses are required in order to avoid confusion in single-line usage. Consider `x cond (1: -1, 2, 3: 0, *: 1)` vs `x cond (1: -1, (2, 3): 0, *: 1)`.

Only allow this for `x cond (...)` syntax. For `cond (...)` syntax, multiple cases can simply be `||`-ed together.

**Comment by ericzhang6222** [comment]
Changes proposed in this ticket to support following syntax:
- `cond ((1 > 0 && 3 > 2): 1, (2 > 3) || (1 < 0): 2, *:1 + 2)`
- `let a = cond (cond (1 > 2 : 1, * : 11) < 2 : 1, 2 < 3: 2, *:1 + 2);a * 10`
- `let a = 2; a cond (1 :1 + 10, (2,3) : 2, *:1 + 2)`
- `let a = 2;
	a cond (
		1:"lo",
		(2,3): "med",
		*: "hi")`
- `let a = 2; a cond ( a cond ((1,2) : 1): "A", (2, 3): "B", *: "C")`
- `let a = 1; a cond ( cond (2 > 1 : 1): "A", (2, 3): "B", *: "C")`
- `let a = 1; cond ( a cond (1 : 1) : "A", 2: "B", *: "C")`
