### ISSUE TITLE
Nicer formatting for nearly-round numbers

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#19]
This is kind of annoying:

```sh
$ go run ./cmd/arrai eval '//.math.cos(//.math.pi/3)'
0.5000000000000001
```

And it turns out that lowering the number by one ulp outputs `0.5` instead.

A handy improvement would be to test nearby numbers (within 1 or 2 ulp, perhaps) and use the shortest representation.

A more sophisticated algorithm might use a formula like "ulp_distance + w*len(representation)", with _w_ chosen to strike a balance between {distance from the actual number too great} and {string representation too long}.

Is it possible to analyze the structure of the number to detect the potential for improvement without actually triggering multiple passes of the formatter?

**Comment by ChloePlanet** [comment]
Fixed.
