### ISSUE TITLE
Error while installing arrai (sync_xlsx.go)

### ISSUE THREAD

**Issue by orlade** [arr-ai/arrai#194]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Description

Error while installing arrai

### Steps to Reproduce
1. `go get -v -u github.com/arr-ai/arrai/cmd/arrai`

**Expected behavior:**
Arr.ai is downloaded and installed

**Actual behavior:**
Download and/or install fails

* Debug&Crash Output

```
go get -v -u github.com/arr-ai/arrai/cmd/arrai
github.com/arr-ai/arrai (download)
created GOPATH=/home/oliver/go; see 'go help gopath'
github.com/anz-bank/pkg (download)
github.com/arr-ai/frozen (download)
[...]
get "golang.org/x/text/encoding": verifying non-authoritative meta tag
get "golang.org/x/text/encoding/internal/identifier": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/encoding/internal/identifier?go-get=1
get "golang.org/x/text/encoding/internal/identifier": verifying non-authoritative meta tag
github.com/urfave/cli (download)
github.com/cpuguy83/go-md2man (download)
golang.org/x/sys/internal/unsafeheader
github.com/arr-ai/wbnf/errors
google.golang.org/protobuf/internal/flags
[...]
github.com/arr-ai/proto
github.com/arr-ai/arrai/cmd/arrai
# github.com/arr-ai/arrai/cmd/arrai
../go/src/github.com/arr-ai/arrai/cmd/arrai/sync_xlsx.go:19:28: sheet.Rows undefined (type *xlsx.Sheet has no field or method Rows)

$ arrai
arrai: command not found
```

### Your Environments

Ubuntu 18 on WSL (Windows 10 Pro), new installation of go 1.14. Same on a new Ubuntu instance on Docker.

```sh
$ go version

go version go1.14.2 linux/amd64
```

**Comment by orlade** [comment]
Reverted to go 1.10 via `apt`:

```
$ go version
go version go1.10.4 linux/amd64
```

`go get` finishes with:

```
[...]
github.com/urfave/cli (download)
github.com/cpuguy83/go-md2man (download)
github.com/arr-ai/hash
# github.com/arr-ai/hash
../../go/src/github.com/arr-ai/hash/arch_wasm.go:7:19: bigEndian redeclared in this block
        previous declaration at ../../go/src/github.com/arr-ai/hash/arch_amd64.go:7:19
$ echo $?
2
```

`arrai` is still not found.

**Comment by marcelocantos** [comment]
Looks like a problem with Go modules. For now, the workaround is to git clone the repo and `go get -v -u ./cmd/arrai`.

**Comment by nofun97** [comment]
@orlade it's most likely a dependency issue with xlsx. Do you by any chance have the library xlsx in your machine?

**Comment by marcelocantos** [comment]
This is looking like a hard problem to solve in a way that just works for everyone. We'll document a more robust source-level approach that requires `git clone ...` and also work on publishing mac/linux/win binaries across commons archs for more casual users.

**Comment by marcelocantos** [comment]
The README instructions should work now.

**Comment by orlade** [comment]
Now I get:

```
go install ./cmd/arrai
cmd/arrai/shell.go:4:2: use of internal package not allowed
cmd/arrai/eval.go:11:2: cannot find package "github.com/urfave/cli/v2" in any of:
        /usr/lib/go/src/github.com/urfave/cli/v2 (from $GOROOT)
        /home/oliver/go/src/github.com/urfave/cli/v2 (from $GOPATH)
Makefile:4: recipe for target 'install' failed
make: *** [install] Error 1
```

Seems like it's because I have go 1.10 (the default version for simpletons who try to apt install), and urfave v2 requires 1.11+. Updated to go 1.14 and it worked. Might want to update the README to state it as a dependency?
