### ISSUE TITLE
Relation builder requires extra space

### ISSUE THREAD

**Issue by dancantos** [arr-ai/arrai#22]
Syntax for building a relation with fields declared at the start requires an extra space

broken: `{|a,b| (1, 2), (3, 4)}`
working: `{ |a,b| (1, 2), (3, 4)}`

This issue is a remnant of the old set notation `{|...|}`. Atempting to remove `{|` and `|}` from the list of tokens produces a panic.

**Comment by ChloePlanet** [comment]
Fixed.
