### ISSUE TITLE
Rethink some API signatures

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#230]
The one that comes to mind is `//seq.sub(s, old, new)`. To effectively leverage currying semantics, the "subject" of a function should come last. In this case, `s` is a natural subject, since it is the value being transformed, so the signature should read `//seq.sub(old, new, s)`. This allows techniques like the following:

```arrai
let rmspace = //seq.sub(" ", "");
[rmspace("hello world"), rmspace("a b c")]
```

Review the entire extant API to see whether any functions should be thus reworked.

**Comment by ericzhang6222** [comment]
```
let rmspace = //seq.sub(" ", "");
[rmspace("hello world"), rmspace("a b c")]
```
Above syntax has been done, only change API signature in this ticket.

**Comment by ericzhang6222** [comment]
Fixed by https://github.com/arr-ai/arrai/pull/240
