### ISSUE TITLE
Refactor //str and //seq

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#234]
Some functions currently in `//str` belong in `//seq`. Review and move.

**Comment by nofun97** [comment]
@ericzhang6222 we want to move a few functions from `//str` to `//seq`. These are the functions.
1. `contains`
2. `sub` 
3. `split` 
4. `has_prefix` 
5. `has_suffix` 
6. `join`

Currently these functions only work on `string`, you need to make them work for `array` and `bytes` too now

**Comment by ericzhang6222** [comment]
> @ericzhang6222 we want to move a few functions from `//str` to `//seq`. These are the functions.
> 
> 1. `contains`
> 2. `sub`
> 3. `split`
> 4. `has_prefix`
> 5. `has_suffix`
> 6. `join`
> 
> Currently these functions only work on `string`, you need to make them work for `array` and `bytes` too now

Thx @nofun97

**Comment by ericzhang6222** [comment]
Following funcs should be moved to STD SEQ and SEQ will support string, byte array and array:
```
contains
sub
split
has_prefix
has_suffix
join
```

**Comment by ericzhang6222** [comment]
Fixed by https://github.com/arr-ai/arrai/pull/240
