### ISSUE TITLE
allow extra elements in pattern matching

### ISSUE THREAD

**Issue by ChloePlanet** [arr-ai/arrai#238]
### Use-cases
As mentioned in #132 and #190, pattern matching as below needs to be supported:
- fix `let = [1, 2]; x` (should fail)
- `let [x, y, ...] = [1, 2, 3]; x + y`  Should pass.
- `let [_, ...t] = [1, 2, 3, 4, 5]; t sum . ` Should pass.
- `[a, b, c, ...t]` allows extra elements in addition to the explicitly bounds ones and binds `t` to an array of them. (Maybe...)
- `(m: x, n: y, ...t)` allows extra elements in addition to the explicitly bounds ones and binds `t` to a tuple of them.
- `{a: x, b: y, ...t}` allows extra elements in addition to the explicitly bounds ones and binds `t` to a dict of them.
- `[a, ...t, b, c]`. The `...t` part can appear anywhere. (Maybe...)
- `let (:lower, :upper, ...) = //str; 1`
- `[a, b, ...t, c, d, ...u, e, f]`. Multiple `...` parts may lead to non-deterministic bindings, depending on the constraints imposed by patterns, a&ndash;f. (Maybe not...)

### References
- #132

**Comment by anzdaddy** [comment]
The following fails to fail:
```arrai
@> let [x] = [1, 2]; x
1
```
No need to fix it separately. Just keep it in mind as part of implement this feature.
