### ISSUE TITLE
Version flag for binary

### ISSUE THREAD

**Issue by nydrani** [arr-ai/arrai#246]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Current arrai Version
It would be nice to be able to check for the current build version of arrai. Either by date or commit hash.

### Use-cases
It would be great for debugging as well as for issues. E.g. Provide arrai build version for bug reproducability.

### Attempted Solutions
```
$ arrai v
build version: 834131ab82c7878c8e8
etc
```

Needs to work in CI and the Makefile. The Makefile option is important because the main [README](https://github.com/arr-ai/arrai#install) recommends installing from source on Unix-like platforms.

For Makefile versioning, we also need to mark builds as dirty if the git repo isn't clean. There are three scenarios to consider:

1. Clean and version-tagged
    ```bash
    $ arrai v
    arrai v0.123.0 darwin/amd64
    ```
1. Clean but no version tag:
    ```bash
    $ arrai v
    arrai 751a975944edadf56a2558a8a21eebcfd47fc52e~3 = v0.123.0 darwin/amd64
    ```
1. Dirty (local working tree changes, including untracked files) and version-tagged:
    ```bash
    $ arrai v
    arrai DIRTY-v0.123.0 darwin/amd64
    ```
1. Dirty (local working tree changes, including untracked files) but no version tag:
    ```bash
    $ arrai v
    arrai DIRTY-751a975944edadf56a2558a8a21eebcfd47fc52e~3 = v0.123.0 darwin/amd64
    ```

Do likewise for `arrai v -v`.

`~3 = v0.123.0` indicates that v0.123.0 is three commits behind HEAD.

**Comment by ericzhang6222** [comment]
CI Release update is done and merged to master branch by https://github.com/arr-ai/arrai/pull/395

**Comment by ericzhang6222** [comment]
Changed the different logs behind HEAD from
```
$ arrai v
arrai 751a975944edadf56a2558a8a21eebcfd47fc52e (~3 = v0.123.0) darwin/amd64
```
to 
```
$ arrai v
arrai 751a975944edadf56a2558a8a21eebcfd47fc52e (from v0.123.0) darwin/amd64
```
as https://github.com/arr-ai/arrai/issues/456
