### ISSUE TITLE
Byte array syntax

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#257]
There is currently no way to express a byte array literal. Introduce the following syntax (from [Erlang's bit syntax](http://erlang.org/doc/programming_examples/bit_syntax.html)):

```arrai
@> <<"Hello, world!", 10>>
<<"Hello, world!\n">>
```

In general, `<<...>>` bracketing a comma-separated list of strings and numbers (0-255). The strings are interpreted as UTF-8 byte sequences. The result is the concatenation of all the elements as a single byte array.

Note: it is proposed to use `<<>>` identifying empty bytes set, `<<''>>` is valid syntax, and `<<>>` is more concise.

Survey tests and documentation to update syntax for byte arrays. Usages of `//unicode.utf8` and `@byte` are prime candidates.

**Comment by ericzhang6222** [comment]
Note: it is proposed to use `<<>>` identifying empty bytes set, `<<''>>` is valid syntax, and `<<>>` is more concise.

**Comment by marcelocantos** [comment]
As an extension, `<<...>>` could be an operator instead of a literal. Then you could write this:
```arrai
let intro = "I know my ";
let A = 65;
<<intro, A, A + 1, A + 2, "s!">>
```

**Comment by marcelocantos** [comment]
As a further extension, `<<...>>` could also be a valid pattern. To detect a PKZIP payload and extract the content after the header:
```arrai
let <<"PK", 3, 4, content>> = zipfile; ...
```

**Comment by marcelocantos** [comment]
Reopening, since docs haven't been surveyed and updated. Also, https://github.com/arr-ai/arrai/pull/321#discussion_r429839965
