### ISSUE TITLE
Need to fix documentation

### ISSUE THREAD

**Issue by rohit-anz** [arr-ai/arrai#26]
We need to fix the documentation by mentioning which all functions  are available and how can we use those functions. It will increase the readability and usability.

**Comment by marcelocantos** [comment]
Most functions are now documented, but we need review and identify any gaps.

**Comment by nofun97** [comment]
most stdlib is documented, only `std-grammar` left, @marcelocantos will write it.

**Comment by nofun97** [comment]
Closing this, moving it to #266
