### ISSUE TITLE
pattern matching in cond

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#288]
Several changes required here:

1. For consistency with `let` syntax, all conditions must have `(...)` syntax, not just multi-valued conditions:
    Before:
    ```
    let a = 1; let b = 2; x cond (a: 10, b: 20)
    ```
    After:
    ```
    let a = 1; let b = 2; x cond ((a): 10, (b): 20)
    ```
1. Remove `*` as a special case. `_` will work as a substitute without any special coding required.
1. Change the overall syntax from `cond (...)` and `expr cond (...)` to `cond {...}` and `expr cond {...}`. This to more clearly differentiate outer bracketing from the conditions: `x cond {(1): 10, (2): 20}`.

The `cond {...}` form without a LHS argument doesn't require pattern matching, since there is no value to match against. However, it's best to make the changes to both to maintain consistent syntax. 

Following piece will be done later:
Since `cond {...}` is simply a shorthand for `true cond {...}`, they should be given the same semantics, and so pattern matching should still work, e.g.: `cond {{t}: t}` should evaluate to `()`.

**Comment by marcelocantos** [comment]
I figured out a fairly safe model for the with-argument syntax. Here's a common mistake:

```arrai
x cond {y: 42, z: 43}
```

This will always match the first case, bind `y` to the value of `x`, and then evaluate `42`. It is almost certain that this was a mistake and the intent was really this:

```arrai
x cond {(y): 42, (z): 43}
```

We can catch these mistakes by simply disallow bare identifiers as cases. The only exception would be the final case, with two conditions:

1. The corresponding result expression must use the bound name (unless it is `_`).
1. There must be at least one other case preceding it.

Under such constraints, this would be allowed:

```arrai
x cond {(y): 42, z: $"unexpected value: ${z}"}
```

But these wouldn't:

```arrai
x cond {y: 42 + y, z: $"unknown: ${z}"}   # y isn't the final case; z is unreachable.
x cond {(y): 42, z: 43}                   # z isn't used. Match _ instead.
x cond {z: 43 + z}                        # No other cases. Use 43 + x instead.
```

**Comment by ericzhang6222** [comment]
Confirmed with @marcelocantos, now the `cond {...}` form without a LHS argument doesn't require pattern matching, since there is no value to match against. However, it's best to make the changes to both to maintain consistent syntax still.
