### ISSUE TITLE
wbnf ignores space character in character class

### ISSUE THREAD

**Issue by orlade** [arr-ai/arrai#315]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Description

Using a `[` character class `]` in a wbnf grammar ignores spaces within the square brackets, making it difficult to match the space character specifically.

### Steps to Reproduce

1. `@> //grammar -> (.parse(.lang.wbnf, "grammar", "x -> [ ];") -> \x .parse(x, "x", " "))`

**Expected behavior:**

`('': ' ')`

**Actual behavior:**

```
@> //grammar -> (.parse(.lang.wbnf, "grammar", "x -> [ ];") -> \x .parse(x, "x", " "))
2020-05-24T18:28:05.9247234+10:00 error_message= INFO
@> //grammar -> (.parse(.lang.wbnf, "grammar", "x -> [ a];") -> \x .parse(x, "x", " "))
2020-05-24T18:28:20.5226789+10:00 error_message=
parse failed
└── rule(x) -
    ├── expect:
    │   :1:1:
    │   (?m)\A([a])
    ├── actual:
    │   :1:1:
    │
    └── {ident:x term:x scope:{m:{root:0xc0004abf40 count:1}}}
 INFO
```

### Your Environments
```sh
$ go version
go version go1.14 linux/amd64

```

**Comment by orlade** [comment]
Messing around a bit, found a workaround:

```
@> //grammar -> (.parse(.lang.wbnf, "grammar", "x -> [[:blank:]];") -> \x .parse(x, "x", " "))
('': ' ')
```

**Comment by marcelocantos** [comment]
`\_` matches a space.
