### ISSUE TITLE
Inconsistent index out of range on holey arrays

### ISSUE THREAD

**Issue by orlade** [arr-ai/arrai#356]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Description

Probably a duplicate but I'm not sure what of.

### Steps to Reproduce

```
@> [1,,3] >> \t t * 2
[2, , 6]
@> [1,,2] >> \t t * 2
2020-06-01T10:19:45.4082434+10:00 error_message=runtime error: index out of range [4] with length 4

.:1:8:
[1,,2] >> \t t * 2 INFO 
```

Also when mapping:

```
@> [1,3] >> \t t * 2
[2, 6]
@> [1,,3] >> \t t * 2
[2, , 6]
@> [1,,,3] >> \t t * 2
2020-06-01T10:31:19.9842297+10:00 error_message=runtime error: index out of range [-1]

.:1:9:
[1,,,3] >> \t t * 2 INFO
```

### Your Environments
```sh
$ go version
go version go1.14 linux/amd64

```

**Comment by orlade-anz** [comment]
Urk, it's actually nondeterministic:

```
ladeo@Olivers-MacBook-Pro ~ % arrai eval '[1,,2] >> \t t * 2'
[2, , 4]
ladeo@Olivers-MacBook-Pro ~ % arrai eval '[1,,2] >> \t t * 2'
INFO[0000] runtime error: index out of range [4] with length 4

.:1:8:
[1,,2] >> \t t * 2
```

**Comment by orlade-anz** [comment]
Turns out the non-determinism is related to enumerating the elements of a set when turning it into an array; depending on which element was picked first, it may or may not expose a bug in the conversion logic which doesn't account for the existence of holes.
