### ISSUE TITLE
Empty string is a *rel.genericSet instead of rel.String

### ISSUE THREAD

**Issue by nofun97** [arr-ai/arrai#36]
Doing
```shell
$ arrai e '""'
{}
```

Internally an empty `*rel.genericSet` can not be converted to `rel.String`

@marcelocantos suggested `Set.AsString() (string, bool)` method

**Comment by marcelocantos** [comment]
Is this resolved?

**Comment by nofun97** [comment]
yes, for some reason the PR doesn't close this.
