### ISSUE TITLE
panic when matching tuple against dict pattern in cond

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#372]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Description

When a dict pattern tries to match a tuple, `cond` panics instead of falling through to the next condition.

### Steps to Reproduce
1. `() cond {{1:2}: 42, _: 43}`

**Expected behavior:**

43

**Actual behavior:**

panic: (s: DATETIME) is not a dict

**Comment by ericzhang6222** [comment]
Fixed by #367
