### ISSUE TITLE
Return `stream` instead of `sequence` in the grpc example

### ISSUE THREAD

**Issue by ChloePlanet** [arr-ai/arrai#44]
The grpc example: https://github.com/arr-ai/arrai/tree/master/examples/grpc

## The current generated proto text
```protobuf
//   THIS IS AUTOGENERATED BY sysl   //
syntax = "proto3";

package github.com/foo/foo;

option go_package = "github.com/foo/foo";

message Customer {
    string customerID = 1;
    string dob = 2;
}

message Account {
    string accountID = 1;
    string opened = 2;
    double balance = 3;
}

service Foo {
    rpc Getcustomer() returns (sequence of Customer) {}
}

```

## The expected proto
There are two possible results depend on the user's intention:
1. 
```diff
+ message Customers {
+     repeated Customer customers = 1;
+ }

service Foo {
-     rpc Getcustomer() returns (sequence of Customer) {}
+     rpc Getcustomers() returns (Customers) {}
}
```
2. 
```diff
service Foo {
-     rpc Getcustomer() returns (sequence of Customer) {}
+     rpc Getcustomers() returns (stream Customer) {}
}
```

**Comment by springwiz** [comment]
@ChloePlanet The issue description is incomplete, you need to describe, how does the app.arrai look like for both the above scenarios. You have only described the grpc output needed.

**Comment by marcelocantos** [comment]
`app.arrai` is only a best-guess at what the input would have been for the original Sysl-based code generator. We need to develop an input stage that mirrors the input to the Sysl codegen transform views.

**Comment by marcelocantos** [comment]
I'm currently working on migrating the Go-server codegen to arr.ai and I'll need to look at this as I do it.
