### ISSUE TITLE
`(.)` returns a misshapen node error

### ISSUE THREAD

**Issue by nofun97** [arr-ai/arrai#442]
### Description
Running `(.)` returns a misshapen node error.

### Steps to Reproduce
1. evaluate `(.)`

**Expected behavior:**
Returns whatever value bind to `.`

**Actual behavior:**
```
INFO[0000] misshapen node AST: (
  @choice: [0, 6],
  cdelim: ('': 2‣")"),
  identpattern: (IDENT: ('': 1‣.)),
  odelim: ('': 0‣"("),
)
```

### Your Environments
```sh
$ go version
go version go1.14.2 darwin/amd64

```

**Comment by ericzhang6222** [comment]
Correct sample:
```
$ arrai e '[1,2,3] => (.)'
[1, 2, 3]
```

**Comment by ericzhang6222** [comment]
@marcelocantos the root cause is now `(.)` is an ident pattern and not an ident.  And user can use `.`  to instead still, so like `[1,2,3,4] -> (.)` can be changed to `[1,2,3,4] -> .` always. As `(.)`  and `.`  are totally different now, so I think this is an invalid bug.

**Comment by anzdaddy** [comment]
It is incorrectly parsed as an IdentPattern. This needs to be fixed.

**Comment by ericzhang6222** [comment]
The base failure case is:
```
@> let (x) = 2; x
2
```
(x) is parsing as a name binding for x, where it should parse as an expression and fail because x isn't bound.
The expected result for `let (x) = 2;x` is:
```
$ arrai e 'let (x) = 2;x'
INFO[0000] "x" not in scope

.:1:1:
let (x) = 2;x 
```
