### ISSUE TITLE
Incorrect --version for dirty repos

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#456]
```
$ arrai --version
arrai 402568cbf36140184fbe86d4db549e82dd80f9fd~5 = v0.64.0 linux/x86_64
$ git log --graph --oneline
*   402568c (HEAD -> chloe/bind-grammar, origin/chloe/bind-grammar) Merge branch 'master' into chloe/bind-grammar
|\  
| * becd25b (tag: v0.64.0, origin/master, origin/HEAD, master) Version flag makefile changes (#450)
* | 7d4d2d7 lint
* | 78e5d4a feat: bind hook
* | a051a36 wip: bind hook
* | 07d09d6 add Bindings to Pattern
|/  
* aed2a44 (tag: v0.63.0) Add shell commands to the predictions (#454)
```

v0.64.0 is only one commit behind 402568c, not five.

**Comment by ericzhang6222** [comment]
5 is correct as there are 5 commits totally can be merged back to master branch(tag v0.64.0)

**Comment by ericzhang6222** [comment]
@marcelocantos, I think 5 is correct. After branch `chloe/bind-grammar` merged `v0.64.0` code from `master`, it has 5 commits will be merged to `master`. And if we review it from timeline, when these 5 commits are merged to `master` the timestamp is later than `v0.64.0` too, so I think it makes sense to match rule "~3 = v0.123.0 indicates that v0.123.0 is three commits behind HEAD." in #246.

**Comment by ericzhang6222** [comment]
Discussed with @marcelocantos, it can simplify this for now and just say this:
```
arrai ce1bb83bf36140184fbe86d4db549e82dd80f9fd (from v0.63.0) linux/x86_64
```

**Comment by ericzhang6222** [comment]
Related to #246
