### ISSUE TITLE
Implement fallbacks in pattern matching

### ISSUE THREAD

**Issue by anzdaddy** [arr-ai/arrai#469]
Arr.ai pattern matching needs support for access fallbacks. If you can write:
```arrai
let middle = cust.details?.name.middle?:""
```
then you should also be able to write
```arrai
let (details?: (name: (:middle?:""))) = cust
```
This can be extended to other pattern forms, e.g.:
```arrai
let [x, y, z?:0] = [1, 2]; // or [1, 2, 3]
let {'ids'?: ids:[]} = {'ids': [1, 2]}
```

(roughly equivalent to...
```arrai
let [x, y] = arr; let z = arr(2)?:0; ...
let ids = dict('ids')?:[]
```
)

**Comment by ChloePlanet** [comment]
Possible Approach:
1. move `tail` definition to `patternterms` macro in `arrai.wbnf` according to #313 
2. add a `CallgetPattern` (or other more proper name) to handle the case similar to `compileCallGet` in `compile.go`
3. tests and docs

**Comment by ChloePlanet** [comment]
`(x?: (y: (z?: w:42)))`

**Comment by marcelocantos** [comment]
Also:
```arrai
(x?: (y: (
    z?: w:42,
    a?: b:43,
    :c?:44,
)))
```
