### ISSUE TITLE
`//os.file` does not allow dynamic root

### ISSUE THREAD

**Issue by nofun97** [arr-ai/arrai#537]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Description
`//os.file` script does not work well when it is imported from a different file. For example, given this directory structure.

```
├── a.arrai
├── test.txt
└── b
    └── c.arrai
```

`a.arrai` contains `//os.file("test.txt")` and `b/c.arrai` contains `//{./../a.arrai}`.

### Steps to Reproduce
With the above structure run `arrai c.arrai` (current directory in `b`)

### Expected behavior
prints what is in `test.txt`

### Actual behavior
```
INFO[0000] open a.txt: no such file or directory

../a.arrai:1:3:
//os.file('a.txt')

c.arrai:1:5:
//{./../a.arrai}
```

### Your Environment
```sh
$ arrai info
Version    : DIRTY-v0.107.0
Git commit : 9b0f4570f8bc49a89650907b806e02f014e887d6
Date       : 2020-07-31T01:21:18Z
OS/arch    : darwin/amd64
Go version : go1.14.4 darwin/amd64
```

**Comment by nofun97** [comment]
Running `arrai b/c.arrai` in root directory works.

**Comment by anzdaddy** [comment]
This is correct behaviour. `//os.file` is not "importing" relative to the source, but opening a file relative to the process's current directory. We eventually want to support importing of arbitrary resources, but this will be via `//{./a.txt}` instead of `//os.file`.
