### ISSUE TITLE
A external repo under arr-ai for testing external import

### ISSUE THREAD

**Issue by ChloePlanet** [arr-ai/arrai#64]
### Current arrai Version
v0.1.0 4add794

### Use-cases
Replace [ChloePlanet/arrai-examples](https://github.com/arr-ai/arrai/pull/51/files/aedf1f50f0975cc61d91e0af66b1f3e54eb46124#diff-326163bbeef8e851e67c34d52bd7f799) with better test case

**Comment by ChloePlanet** [comment]
Another issue:
```
panic: failed to import https://github.com/ChloePlanet/arrai-examples/empty.json - no such module, and request https://github.com/ChloePlanet/arrai-examples/empty.json failed: 404 Not Found
```
this might be an intermittent problem due to network. We might need to think about how to test this in a more decoupled way.

**Comment by marcelocantos** [comment]
There's a more general problem that this can significantly increase test running time. Maybe we should tag this so that, by default, it doesn't run on the developer's machine, but still runs in CI.
