### ISSUE TITLE
make importing standard libraries lazy

### ISSUE THREAD

**Issue by ChloePlanet** [arr-ai/arrai#67]
### Current arrai Version
v0.1.0 4add794

### Use-cases
Make importing standard libraries lazy.
For instance:
```arrai
let k = //./pkg1 if 3 < 2 else //./pkg2
k * 2
```
What we want is the packages can be lazy compiled (this _lazy_ means the same in _lazy load_): in the case above, arrai only compiles `pkg2.arrai`.

**Comment by ericzhang6222** [comment]
This feature has been done, no code change.
