### ISSUE TITLE
Inconsistent surrounding double quotes in string output

### ISSUE THREAD

**Issue by anzboi** [arr-ai/arrai#74]
### Description
Arrai string output is inconsistent when it comes to surrounding double quotes

For example
```
$ arrai e '"ab"'
ab

$ arrai e '"a" + "b"'
"ab"
```

**Expected behavior:**
Either have double quotes or don't have them in output. This is probably not trivial because sometimes you want the quotes (eg: you want your output to be valid arrai) or not (producing templated text).

**Actual behavior:**
Quotes are inconsistent

### Your Environments
```sh
$ go version
go version go1.14 darwin/amd64
```

**Comment by marcelocantos** [comment]
Fixed in master.
