### ISSUE TITLE
Implement syntax highlighting

### ISSUE THREAD

**Issue by marcelocantos** [arr-ai/arrai#9]
TextMate format is supported by VSCode and Sublime (and TextMate, of course) so it might be a good initial target.

This is an AST-to-AST transform problem, so it should leverage the grammar embedding facility soon to be introduced. However, it's almost certainly worth doing it by hand the first time around to get a feel for the kind of problem it is.

**Comment by nofun97** [comment]
created a repo [vscode-arrai](https://github.com/arr-ai/vscode-arrai)
